name: 'Snapshot Review'
description: 'Produces a visual snapshot diff for review purposes'
author: 'Ritchie Comley'
inputs:
  token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  working-directory:
    description: 'Relative path under $GITHUB_WORKSPACE where the repository was checked out.'
    required: false
  ref:
    description: |
      Git reference (e.g. branch name) from which the changes will be detected.
      This option is ignored if action is triggered by pull_request event.
    required: false
  base:
    description: |
      Git reference (e.g. branch name) against which the changes will be detected. Defaults to repository default branch (e.g. master).
      If it references same branch it was pushed to, changes are detected against the most recent commit before the push.
      This option is ignored if action is triggered by pull_request event.
    required: false
outputs:
  changes:
    description: JSON array with names of all filters matching any of changed files
runs:
  using: 'node16'
  main: 'src/index.js'
