name: 'Snapshot Review'
description: 'Produces a visual snapshot diff for review purposes'
author: 'Ritchie Comley'
inputs:
  token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  snapshots-dir:
    description: 'Relative path under $GITHUB_WORKSPACE where your snapshots are located'
    required: true
  branch-name:
    description: |
      Git reference (e.g. branch name) from which the changes will be detected.
    required: true
  base-branch-name:
    description: |
      Git reference (e.g. branch name) against which the changes will be detected.
    required: true
  pr-number:
    description: |
      The number of the PR that triggered this action
    required: true
  review-repo-remote-path:
    description: |
      The repo where the snapshot diffs will be published
    required: true
outputs:
  changes:
    description: JSON array with paths of all files with snapshot changes detected
  diffs:
    description: A zip file containing the snapshot diff images
runs:
  using: 'node16'
  main: 'dist/index.js'
