name: Automated tests
on: [pull_request]
jobs:
  runs-snapshot-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check snapshots
        id: check-snapshots
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          snapshots-dir: 'test-snapshots'
          base-branch-name: ${{ github.base_ref }}
          branch-name: ${{ github.head_ref }}
          pr-number: ${{ github.event.number }}
      - name: Save diff to file
        run: echo ${{ steps.check-snapshots.outputs.diffs }} > diffs.zip
      - name: Archive diff zip file artifact
        uses: actions/upload-artifact@v3
        with:
          name: diffs
          path: |
            diffs.zip


 